// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbCsdEaN_Vm7kY1WCthNecBPkVXFUFSBw',
    appId: '1:652032442941:web:315128d99734529ce5e054',
    messagingSenderId: '652032442941',
    projectId: 'taskmanager-2e6df',
    authDomain: 'taskmanager-2e6df.firebaseapp.com',
    storageBucket: 'taskmanager-2e6df.appspot.com',
    measurementId: 'G-13LHNFLQN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyf0a5dlkpc-aslRUyunJ5SKm3OUtH7sw',
    appId: '1:652032442941:android:464796ff4629f3dae5e054',
    messagingSenderId: '652032442941',
    projectId: 'taskmanager-2e6df',
    storageBucket: 'taskmanager-2e6df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRENdEDCH4UA1ui3NJMfeq1qSyNHgbv0E',
    appId: '1:652032442941:ios:018e6a2d20cfd1f7e5e054',
    messagingSenderId: '652032442941',
    projectId: 'taskmanager-2e6df',
    storageBucket: 'taskmanager-2e6df.appspot.com',
    iosClientId: '652032442941-2qisi5u88io0s506o9c7plbu5rcbjg52.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRENdEDCH4UA1ui3NJMfeq1qSyNHgbv0E',
    appId: '1:652032442941:ios:018e6a2d20cfd1f7e5e054',
    messagingSenderId: '652032442941',
    projectId: 'taskmanager-2e6df',
    storageBucket: 'taskmanager-2e6df.appspot.com',
    iosClientId: '652032442941-2qisi5u88io0s506o9c7plbu5rcbjg52.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );
}
